version: 0.2

phases:
  install:
    runtime-versions:
    nodejs: 8
    commands:
      - npm install
  build:
    commands:
      - npm run-script install
  artifacts:
    files:
      - '**/*'
    base-directory: build